#!/usr/bin/env python3

import math
import json

# Wavelength of initial perturbation
L = 0.030

# Frequency of oscillation (Hz)
F = 96.4

# Magnitude of oscillation
M = 256*9.81

NC = 64

# CFL
cfl = 0.8

# Periods of oscillation
tend = 2/96.4

# Numerical setup
d0 = 0.
x0 = 0
x1 = 2*L
y0 = 0
y1 = 10*L
z0 = 0
z1 = 2*L

Nx = 2*NC - 1
Ny = 10*NC - 1
Nz = 2*NC - 1

eps = 1e-6

dt = 6e-7
Nt = int(tend/dt)
Ns = int(Nt/100)

#Configuration case dictionary
data = {
    # Logistics =============================
        #'case_dir'          : '\'.\'',
        'run_time_info'     : 'T',
    # =======================================

    # Computational Domain ==================
        'x_domain%beg'      : x0,
        'x_domain%end'      : x1,
        'y_domain%beg'      : y0,
        'y_domain%end'      : y1,
        'z_domain%beg'      : z0,
        'z_domain%end'      : z1,
        'm'                 : Nx,
        'n'                 : Ny,
        'p'                 : Nz,
        'cyl_coord'        : 'F',
        # 'cfl_dt'            : 'T',
        # 'cfl'               : 0.7,
        # 't_start'           : 0,
        # 't_stop'             : tend,
        # 'n_save'            : 100,
        'dt'                : dt,
        't_step_start'      : 0,
        't_step_stop'       : Nt,
        't_step_save'       : Ns,
    # =======================================

    # Simulation Algorithm ==================
        'model_eqns'        : 3,
        'alt_soundspeed'    : 'F',
        'adv_alphan'        : 'T',
        'mixture_err'       : 'F',
        'mpp_lim'           : 'T',
        'time_stepper'      : 3,
        'weno_order'        : 3,
        'mapped_weno'       : 'F',
        'mp_weno'           : 'F',
        'avg_state'         : 2,
        'weno_eps'          : 1e-16,
        'riemann_solver'    : 2,
        'wave_speeds'       : 1,
        'bc_x%beg'          : -2,
        'bc_x%end'          : -2,
        'bc_y%beg'          : -15,
        'bc_y%end'          : -15,
        'bc_z%beg'          : -2,
        'bc_z%end'          : -2,
        'num_patches'       : 2,
        'num_fluids'        : 2,
    # =======================================

    # Database Structure Parameters =========
        'format'            : 1,
        'precision'         : 2,
        'prim_vars_wrt'     : 'T',
        'parallel_io'       : 'T',
    # =======================================

    # Fluid Parameters (Water) ==============
        # 'fluid_pp(1)%gamma'            : 1.E+00/(6.12E+00-1.E+00),
        # 'fluid_pp(1)%pi_inf'           : 6.12E+00*2.13E+08/(6.12E+00-1.E+00),
        'fluid_pp(1)%gamma'            : 1.E+00/(1.08E+00-1.E+00),
        'fluid_pp(1)%pi_inf'           : 0,
    # =======================================

    # Fluid Parameters (Gas) ================
        'fluid_pp(2)%gamma'            : 1.E+00/(1.4E+00-1.E+00),
        'fluid_pp(2)%pi_inf'           : 0.E+00,
    # =======================================

    'bf_y'  : 'T',
    'k_y'   : M,
    'w_y'   : 2*math.pi*F,
    'p_y'   : 0,
    'g_y'   : -9.81,

    # 'sigma' : 0.0206,
    # 'cf_wrt': 'T',

    # water patch ==========================
        'patch_icpp(1)%geometry'    : 13,
        'patch_icpp(1)%hcid'        : 301,
        'patch_icpp(1)%x_centroid'  : x1/2,
        'patch_icpp(1)%y_centroid'  : y1/2,
        'patch_icpp(1)%z_centroid'  : z1/2,
        'patch_icpp(1)%length_x'    : x1,
        'patch_icpp(1)%length_y'    : y1,
        'patch_icpp(1)%length_z'    : z1,
        'patch_icpp(1)%vel(1)'      : 0.0,
        'patch_icpp(1)%vel(2)'      : 0.0,
        'patch_icpp(1)%vel(3)'      : 0.0,
        'patch_icpp(1)%pres'        : 100000,
        'patch_icpp(1)%alpha_rho(1)': eps*950,
        'patch_icpp(1)%alpha_rho(2)': (1-eps)*1,
        'patch_icpp(1)%alpha(1)'    : eps,
        'patch_icpp(1)%alpha(2)'    : 1-eps,
    # ======================================

    # water patch ==========================
        'patch_icpp(1)%geometry'    : 9,
        'patch_icpp(1)%hcid'        : 301,
        'patch_icpp(1)%x_centroid'  : x1/2-L,
        'patch_icpp(1)%y_centroid'  : y1/2-L,
        'patch_icpp(1)%z_centroid'  : 4*L,
        'patch_icpp(1)%length_x'    : L/4,
        'patch_icpp(1)%length_y'    : L/4,
        'patch_icpp(1)%length_z'    : L/4,
        'patch_icpp(1)%vel(1)'      : 0.0,
        'patch_icpp(1)%vel(2)'      : 0.0,
        'patch_icpp(1)%vel(3)'      : 0.0,
        'patch_icpp(1)%pres'        : 105000,
        'patch_icpp(1)%alpha_rho(1)': eps*5.5,
        'patch_icpp(1)%alpha_rho(2)': (1-eps)*1,
        'patch_icpp(1)%alpha(1)'    : eps,
        'patch_icpp(1)%alpha(2)'    : 1-eps,
    # ======================================


}

print(json.dumps(data))
